app/feedbacks/models.py
from app import db

class Feedback(db.Model):
    __tablename__ = 'feedback'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    content = db.Column(db.String(500), nullable=False)

    def __init__(self, user_id=0, content=''):
        self.user_id = user_id
        self.content = content

    def __repr__(self):
        return "<Feedback %s>" % self.id

app/users/models.py
from app import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(100), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.Integer, nullable=False, unique=True)
    password = db.Column(db.String(80), nullable=False)
    entries = db.relationship('Entry', backref='user')
    feedbacks = db.relationship('Feedback', backref='user')

    def __init__(self, name="", phone="", password="", email=""):
        self.email = email
        self.phone = phone
        self.name = name
        self.password = password

    def __repr__(self):
        return "<User %s>" % self.id

app/entries/controllers.py
from flask import request, render_template, Blueprint, json, redirect
from app import db,login_manager
from app.entries.models import Entry
from app.users.models import User
from flask_login import login_required, current_user
from datetime import datetime

mod_entries = Blueprint('entries', __name__)

@login_required
@mod_entries.route('/addEntry', methods = ['POST'])
def add_entry():
    try:
        if request.form['fromto'] == 'from':
            start_lat = 17.4447918
            start_lon = 78.34830979999992
            end_lat = request.form['latitude']
            end_lon = request.form['longitude']
            start = "IIIT, Gachibowli, Hyderabad, Telangana, India"
            end = request.form['address']
        else:
            end_lat = 17.4447918
            end_lon = 78.34830979999992
            start_lat = request.form['latitude']
            start_lon = request.form['longitude']
            end = "IIIT, Gachibowli, Hyderabad, Telangana, India"
            start = request.form['address']
        dateobj = datetime.strptime(request.form['datetime'] + ':00.0', "%Y-%m-%d %H:%M:%S.%f")
        entry = Entry(start_lon, start_lat, end_lon, end_lat, start, end, int(request.form['num']), request.form['info'], dateobj, current_user.id)
        db.session.add(entry)
        user = User.query.filter(User.id == current_user.id).first()
        user.entries.append(entry)
        db.session.commit()
        return json.jsonify(status=True)
    except Exception as e:
        print(e)
        return json.jsonify(status=False)

@login_required
@mod_entries.route('/history', methods = ['GET'])
def history():
    entries = User.query.filter(User.id == current_user.id).first().entries
    f_entries = []
    for entry in entries:
        if entry.done_or_not:
            f_entries.append(entry)
    return render_template('history.html', entries=f_entries, user=current_user)

@login_required
@mod_entries.route('/upcoming', methods = ['GET'])
def upcoming():
    entries = User.query.filter(User.id == current_user.id).first().entries
    f_entries = []
    for entry in entries:
        if not entry.done_or_not:
            f_entries.append(entry)
    return render_template('upcoming.html', entries=f_entries, user=current_user)

@login_required
@mod_entries.route('/matches', methods = ['GET'])
def matches():
    id = request.args.get('id')
    curr_entry = Entry.query.filter(Entry.id == id).first()
    entries = Entry.query.all()
    matches_data = []
    matches_user = []
    for entry in entries:
        if entry != curr_entry:
            if curr_entry.no_of_pass + entry.no_of_pass <= 4:
                if entry.start == curr_entry.start and entry.start == "IIIT, Gachibowli, Hyderabad, Telangana, India":
                    if entry.end_lon - curr_entry.end_lon <= 0.02:
                        if entry.end_lat - curr_entry.end_lon <= 0.02:
                            if (entry.time_of_travel - curr_entry.time_of_travel).seconds / 3600 <= 1:
                                matches_data.append(entry)
                                matches_user.append(User.query.filter(User.id == entry.user_id).first())
                elif entry.end == curr_entry.end and entry.end == "IIIT, Gachibowli, Hyderabad, Telangana, India":
                    if entry.start_lon - curr_entry.start_lon <= 0.02:
                        if entry.start_lat - curr_entry.start_lon <= 0.02:
                            if (entry.time_of_travel - curr_entry.time_of_travel).seconds / 3600 <= 1 or (curr_entry.time_of_travel - entry.time_of_travel) / 3600 <= 1:
                                matches_data.append(entry)
                                matches_user.append(User.query.filter(User.id == entry.user_id).first())
    return render_template('matches.html', matches=matches_data, user=current_user, matches_user=matches_user)

@login_required
@mod_entries.route('/confirmed', methods = ['POST'])
def confirmed():
    try:
        id = request.form['id']
        entry = Entry.query.filter(Entry.id == id).first()
        entry.done_or_not = True
        db.session.commit()
        return json.jsonify(status=True)
    except:
        return json.jsonify(status=False)

app/feedbacks/controllers.py
from flask import request, render_template, Blueprint, json, redirect
from flask_login import login_required, current_user
from app.feedbacks.models import Feedback
from app import db

mod_feedbacks = Blueprint('feedbacks', __name__)

@login_required
@mod_feedbacks.route('/addFeedback', methods = ['POST'])
def add_feedback():
    try:
        feedback = Feedback(current_user.id, request.form['content'])
        db.session.add(feedback)
        db.session.commit()
        return json.jsonify(status=True)
    except:
        return json.jsonify(status=False)

@login_required
@mod_feedbacks.route('/feedback', methods = ['GET'])
def feedback():
    return render_template('feedback.html', user=current_user)

app/users/controllers.py
from flask import request, render_template, Blueprint, json, redirect, url_for
from app import db, login_manager
from app.users.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, login_user, current_user, logout_user

mod_users = Blueprint('users', __name__)

@mod_users.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        try:
            user = User(request.form['name'], request.form['phone'], generate_password_hash(request.form['password'], method='sha256'), request.form['email'])
            db.session.add(user)
            db.session.commit()
            return json.jsonify(status=True)
        except Exception as e:
            print(e)
            return json.jsonify(status=False)
    else:
        return render_template('register.html')

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@mod_users.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        if not current_user.is_anonymous:
            return render_template('dashboard.html', user=current_user)
        return render_template('login.html')
    else:
        user = User.query.filter(User.email == request.form['email']).first()
        if user:
            if check_password_hash(user.password, request.form['password']):
                remember = False
                if request.form['remember'] == 'remember':
                    remember = True
                login_user(user, remember=remember)
                return redirect(url_for('users.dashboard'))
            else:
                return json.jsonify(status=False)
        else:
            return json.jsonify(status=False)

@mod_users.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

@mod_users.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    return render_template('dashboard.html', user=current_user)

@login_required
@mod_users.route('/change-password', methods=['POST'])
def change_password():
    try:
        if check_password_hash(current_user.password, request.form['opw']):
            current_user.password = generate_password_hash(request.form['npw'], method='sha256')
            db.session.commit()
            return json.jsonify(status=True)
        else:
            return json.jsonify(status=False)
    except:
        return json.jsonify(status=False)

@login_required
@mod_users.route('/user-details', methods = ['GET'])
def user_details():
    return render_template('user.html', user=current_user)

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home - {{ user.name.partition(' ')[0] }} - Cab Portal</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>
<body>
    <nav class="navbar sticky-top navbar-toggleable-md navbar-light bg-faded" style="background-color: #c4e187">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/iiit-logo.gif') }}" style="height: 30px;" class="d-inline-block align-top" alt="">
            IIIT-H Cab Portal
        </a>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('users.dashboard') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entries.upcoming') }}">Upcoming</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entries.history') }}">History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('feedbacks.feedback') }}">Feedback</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_details') }}">User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
            </ul>
            <span class="navbar-text">
                {{ user.name }}
            </span>
        </div>
    </nav>

    <div class="jumbotron jumbotron-fluid" style="background-color: #c4e187; padding-top: 2em">
        <h1 class="text-center">Hey! {{ user.name.partition(' ')[0] }}, just fill in these details and we will find you a car pool.</h1>
        <form class="form-inline" onsubmit="return false;">
            <div class="input-group" style="margin: 2em auto 0 auto;width: 50%">
                <div class="input-group-addon form-control-lg">Location</div>
                <input class="form-control form-control-lg" type="text" placeholder="you want to go or want to come from" id="txtPlaces">
            </div>
        </form>
    </div>
    <div class="col-6 offset-3">
        <form onsubmit="return false" style="margin-bottom: 2em">
            <div class="form-group row">
                <label for="name" class="col-3 col-form-label">Name</label>
                <div class="col-9">
                    <input type="text" class="form-control" id="name" value="{{ user.name }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-3 col-form-label">Email address</label>
                <div class="col-9">
                    <input type="email" class="form-control" id="email" value="{{ user.email }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group row">
                <label for="phone" class="col-3 col-form-label">Phone</label>
                <div class="col-9">
                    <input type="text" class="form-control" id="phone" value="{{ user.phone }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="date" class="col-3 col-form-label">Form/To IIIT-H</label>
                <div class="col-4">
                    <label class="form-check-label">
                        <input class="form-check-input fromto" name="fromto" type="radio" value="from" checked="checked">
                        From IIIT-H
                    </label>
                </div>
                <div class="col-3">
                    <label class="form-check-label">
                        <input class="form-check-input fromto" name="fromto" type="radio" value="to">
                        To IIIT-H
                    </label>
                </div>
            </div>
            <div class="form-group row">
                <label for="date" class="col-3 col-form-label">Date of travel</label>
                <div class="col-9">
                    <input class="form-control" type="date" id="date" value="2017-01-01">
                </div>
            </div>
            <div class="form-group row">
                <label for="time" class="col-3 col-form-label">Time of travel</label>
                <div class="col-9">
                    <input class="form-control" type="time" value="00:00" id="time">
                </div>
            </div>
            <div class="form-group row">
                <label for="numberofpeople" class="col-3 col-form-label">Number of people</label>
                <div class="col-9">
                    <select class="form-control" id="numberofpeople">
                        <option value="1" selected="selected">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="otherinfo" class="col-3 col-form-label">Other Information</label>
                <div class="col-9">
                    <textarea class="form-control" id="otherinfo" rows="5"></textarea>
                </div>
            </div>
            <div class="row" id="error-msg" style="margin-top: 1em; display: none;">
                <div class="col-9 offset-3">
                    <div class="alert alert-danger" role="alert">
                        <strong>Oh snap!</strong> Enter valid details and then submit again.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9 offset-3">
                    <button type="submit" id="submit" class="btn btn-success" style="width: 100%;">Find a match</button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC1lizWXXe8kyreskpjn27PNzyhthCl7f8&libraries=places"></script>
    <script type="text/javascript">
        var latitude, longitude, address;
        google.maps.event.addDomListener(window, 'load', function () {
            var options = {
                componentRestrictions: {country: "ind"}
            };
            var places = new google.maps.places.Autocomplete(document.getElementById('txtPlaces'), options);
            google.maps.event.addListener(places, 'place_changed', function () {
                var place = places.getPlace();
                address = place.formatted_address;
                latitude = place.geometry.location.lat();
                longitude = place.geometry.location.lng();
            });
        });
    </script>
    <script>
        var date = new Date().toJSON();
        document.getElementById("date").value = date.slice(0,10);
        var hour = (parseInt(date.slice(11,13))+5)%24;
        if (hour.toString().length < 2) hour = '0' + hour.toString();
        else hour = hour.toString();
        var minute = (parseInt(date.slice(14,16))+30)%60;
        if (minute.toString().length < 2) minute = '0' + minute.toString();
        else minute = minute.toString();
        document.getElementById("time").value = hour+':'+minute;
    </script>
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/tether.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script>
         $('#submit').on('click', function () {
             $.ajax({
                 url: '{{ url_for('entries.add_entry') }}',
                 type: 'POST',
                 data: {
                     fromto: $('.fromto:checked').val(),
                     latitude: latitude,
                     longitude: longitude,
                     address: address,
                     num: $('#numberofpeople').val(),
                     datetime: $('#date').val()+' '+$('#time').val(),
                     info: $('#otherinfo').val()
                 },
                 success: function(response) {
                     console.log($('#date').val()+' '+$('#time').val().slice(0,5))
                     if(response.status == true) {
                         window.location = '{{ url_for('entries.upcoming') }}'
                     }
                     else {
                         console.log(response);
                         $('#error-msg').show();
                     }
                 }
             });
         });
    </script>
</body>
</html>

app/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feedback - {{ user.name.partition(' ')[0] }} - Cab Portal</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>
<body>
    <nav class="navbar sticky-top navbar-toggleable-md navbar-light bg-faded" style="background-color: #c4e187">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/iiit-logo.gif') }}" style="height: 30px;" class="d-inline-block align-top" alt="">
            IIIT-H Cab Portal
        </a>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.dashboard') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entries.upcoming') }}">Upcoming</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entries.history') }}">History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('feedbacks.feedback') }}">Feedback</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_details') }}">User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
            </ul>
            <span class="navbar-text">
                {{ user.name }}
            </span>
        </div>
    </nav>

    <div class="col-6 offset-3" style="padding-top: 2em">
        <form onsubmit="return false" style="margin-bottom: 2em">
            <div class="form-group row">
                <label for="name" class="col-3 col-form-label">Name</label>
                <div class="col-9">
                    <input type="text" class="form-control" id="name" value="{{ user.name }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-3 col-form-label">Email address</label>
                <div class="col-9">
                    <input type="email" class="form-control" id="email" value="{{ user.email }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group row">
                <label for="otherinfo" class="col-3 col-form-label">Message</label>
                <div class="col-9">
                    <textarea class="form-control" id="content" rows="10"></textarea>
                </div>
            </div>
            <div class="row" id="error-msg" style="margin-top: 1em; display: none;">
                <div class="col-9 offset-3">
                    <div class="alert alert-danger" role="alert">
                        <strong>Oh snap!</strong> Enter valid details and then submit again.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9 offset-3">
                    <button type="submit" id="submit" class="btn btn-primary" style="width: 100%;">Submit Feedback</button>
                </div>
            </div>
        </form>
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/tether.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script>
         $('#submit').on('click', function () {
             $.ajax({
                 url: '{{ url_for('feedbacks.add_feedback') }}',
                 type: 'POST',
                 data: {
                     content: $('#content').val()
                 },
                 success: function(response) {
                     if(response.status == true) {
                         window.location = '{{ url_for('users.dashboard') }}'
                     }
                     else {
                         $('#error-msg').show();
                     }
                 }
             });
         });
    </script>
</body>
</html>

app/templates/upcoming.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upcoming - {{ user.name.partition(' ')[0] }} - Cab Portal</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>
<body>
    <nav class="navbar sticky-top navbar-toggleable-md navbar-light bg-faded" style="background-color: #c4e187; margin-bottom: 0">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/iiit-logo.gif') }}" style="height: 30px;" class="d-inline-block align-top" alt="">
            IIIT-H Cab Portal
        </a>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.dashboard') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('entries.upcoming') }}">Upcoming</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entries.history') }}">History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('feedbacks.feedback') }}">Feedback</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_details') }}">User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
            </ul>
            <span class="navbar-text">
                {{ user.name }}
            </span>
        </div>
    </nav>
    {% if entries|length != 0 %}
        <table class="table table-hover">
            <thead>
            <tr>
                <th style="width: 3%; text-align: center;">#</th>
                <th style="width: 35%; text-align: center;">To</th>
                <th style="width: 35%; text-align: center;">From</th>
                <th style="width: 5%; text-align: center;">Number</th>
                <th style="width: 11%; text-align: center;">Date</th>
                <th style="width: 11%; text-align: center;">Time</th>
                <th style="width: 11%; text-align: center;">Matches</th>
                <th style="width: 11%; text-align: center;">Confirmation</th>
            </tr>
            </thead>
            <tbody>
                {% for entry in entries|sort(attribute='time_of_travel', reverse=True) %}
                    <tr>
                        <th scope="row" style="text-align: center;">{{ loop.index }}</th>
                        <td>{{ entry.end }}</td>
                        <td>{{ entry.start }}</td>
                        <td style="text-align: center;">{{ entry.no_of_pass }}</td>
                        <td style="text-align: center;">{{ entry.time_of_travel.strftime('%d %h %Y') }}</td>
                        <td style="text-align: center;">{{ entry.time_of_travel.strftime('%I:%M %p') }}</td>
                        <td class="align-middle text-center" onclick="window.location='{{ url_for('entries.matches') }}?id={{ entry.id }}'"><button type="button" class="btn btn-info">Matches</button></td>
                        <td class="align-middle text-center" onclick="confirmed({{ entry.id }});"><button type="button" class="btn btn-success">Confirmed</button></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h4 class="text-center" style="margin-top: 1em;">No upcoming rides</h4>
    {% endif %}

    <script>
        function confirmed(id) {
            $.ajax({
                 url: '{{ url_for('entries.confirmed') }}',
                 type: 'POST',
                 data: {
                     id: id
                 },
                 success: function() {
                     window.location='{{ url_for('entries.upcoming') }}'
                 }
             });
        }
    </script>

    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/tether.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

app/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.name.partition(' ')[0] }} - Cab Portal</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>
<body>
    <nav class="navbar sticky-top navbar-toggleable-md navbar-light bg-faded" style="background-color: #c4e187">
        <a class="navbar-brand" href="#">
            <img src="{{ url_for('static', filename='img/iiit-logo.gif') }}" style="height: 30px;" class="d-inline-block align-top" alt="">
            IIIT-H Cab Portal
        </a>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.dashboard') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entries.upcoming') }}">Upcoming</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('entries.history') }}">History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('feedbacks.feedback') }}">Feedback</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('users.user_details') }}">User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
            </ul>
            <span class="navbar-text">
                {{ user.name }}
            </span>
        </div>
    </nav>

    <div class="col-6 offset-3" style="padding-top: 2em">
        <form onsubmit="return false" style="margin-bottom: 2em">
            <div class="form-group row">
                <label for="name" class="col-3 col-form-label">Name</label>
                <div class="col-9">
                    <input type="text" class="form-control" id="name" value="{{ user.name }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-3 col-form-label">Email address</label>
                <div class="col-9">
                    <input type="email" class="form-control" id="email" value="{{ user.email }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group row">
                <label for="phone" class="col-3 col-form-label">Phone</label>
                <div class="col-9">
                    <input type="text" class="form-control" id="phone" value="{{ user.phone }}" readonly="readonly">
                </div>
            </div>
            <div class="form-group row">
                <label for="opw" class="col-3 col-form-label">Old password</label>
                <div class="col-9">
                    <input type="password" class="form-control" id="opw">
                </div>
            </div>
            <div class="form-group row">
                <label for="npw" class="col-3 col-form-label">New password</label>
                <div class="col-9">
                    <input type="password" class="form-control" id="npw">
                </div>
            </div>
            <div class="row" id="msg" style="margin-top: 1em; display: block;">
                <div class="col-9 offset-3">
                    <div class="alert alert-warning" role="alert">
                        You will be logged out for security reasons after you successfully change your password.
                    </div>
                </div>
            </div>
            <div class="row" id="error-msg" style="margin-top: 1em; display: none;">
                <div class="col-9 offset-3">
                    <div class="alert alert-danger" role="alert">
                        <strong>Oh snap!</strong> Enter valid details and then submit again.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-9 offset-3">
                    <button type="submit" id="submit" class="btn btn-warning" style="width: 100%;">Change Password</button>
                </div>
            </div>
        </form>
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/tether.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script>
         $('#submit').on('click', function () {
             $.ajax({
                 url: '{{ url_for('users.change_password') }}',
                 type: 'POST',
                 data: {
                     opw: $('#opw').val(),
                     npw: $('#npw').val()
                 },
                 success: function(response) {
                     if(response.status == true) {
                         window.location = '{{ url_for('users.logout') }}'
                     }
                     else {
                         $('#error-msg').show();
                     }
                 }
             });
         });
    </script>
</body>
</html>